version: '2'
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
              LC_ALL: C.UTF-8
              POSTGRES_USER: root
              POSTGRES_PASSWORD: root
              POSTGRES_DB: moss-sk
